# pandas_sql_multi
reproducing this error
